#!/bin/bash
yay -Syu 
yay -S update-grub 
yay -S ly 
yay -S hyprland-nvidia 
yay -S qtfm
yay -S foot 
yay -S leafpad 
yay -S qt6-wayland 
yay -S qt5-wayland 
yay -S wofi 
yay -S midori
yay -S polkit-dumb-agent-git 
yay -S feh
yay -S file-roller
yay -S opencl-nvidia
yay -S unrar
