#!/bin/bash
yay -Syu 
yay -S update-grub ly hyprland-nvidia qtfm foot leafpad qt6-wayland qt5-wayland wofi feh file-roller opencl-nvidia unrar xdg-desktop-portal-hyprland --noconfirm
yay -S polkit-dumb-agent-git 

