#!/bin/bash
yay -Syu 
yay -S update-grub 
yay -S ly 
yay -S hyprland-nvidia 
yay -S pcmanfm 
yay -S foot 
yay -S leafpad 
yay -S icewm 
yay -S qt6-wayland 
yay -S qt5-wayland 
yay -S wofi 
yay -S firefox 
yay -S polkit-dumb-agent-git 



