#!/bin/bash

mkfs.fat -F32 /dev/sd#1

mkfs.ext4 /dev/sd#2

mount /dev/sd#2 /mnt

mkdir -p /mnt/boot/efi

mount /dev/sd#1 /mnt/boot/efi

pacstrap /mnt base linux linux-firmware base-devel git nano wget dhcpcd

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt

echo en_US.UTF-8 UTF-8 >> /etc/locale.gen

locale-gen

echo LANG=en_US.UTF-8 > /etc/locale.conf

echo ty > /etc/hostname

passwd

pacman -S grub efibootmgr os-prober

grub-install

grub-mkconfig -o /boot/grub/grub.cfg

pacman -S sudo

useradd -m ty

passwd ty

echo "ty ALL=(ALL:ALL) ALL" >> /etc/sudoers




